import { createClient } from "@/lib/supabase/server"
import type { IndividualRotationTemplateRecord } from "./types"

type UnknownRecord = Record<string, unknown>

function asRecord(
  value: unknown,
  label: string,
): UnknownRecord {
  if (
    typeof value !== "object" ||
    value === null ||
    Array.isArray(value)
  ) {
    throw new Error(
      `Invalid Individual Rotation template: ${label} must be an object.`,
    )
  }

  return value as UnknownRecord
}

function readPlayerPair(
  match: UnknownRecord,
  camelKey: "teamA" | "teamB",
  snakeKey: "team_a" | "team_b",
  label: string,
): [string, string] {
  const value =
    match[camelKey] ??
    match[snakeKey]

  if (
    !Array.isArray(value) ||
    value.length !== 2 ||
    typeof value[0] !== "string" ||
    typeof value[1] !== "string"
  ) {
    throw new Error(
      `Invalid Individual Rotation template: ${label} must contain exactly two player ids.`,
    )
  }

  return [value[0], value[1]]
}

function readRoundNumber(
  round: UnknownRecord,
  fallback: number,
): number {
  const value =
    round.roundNumber ??
    round.round_number ??
    round.round

  return typeof value === "number" &&
    Number.isInteger(value) &&
    value >= 1
    ? value
    : fallback
}

function readRestingPlayerIds(
  round: UnknownRecord,
  label: string,
): string[] {
  const value =
    round.restingPlayerIds ??
    round.resting_player_ids ??
    round.sitouts ??
    []

  if (
    !Array.isArray(value) ||
    value.some(
      (playerId) =>
        typeof playerId !== "string",
    )
  ) {
    throw new Error(
      `Invalid Individual Rotation template: ${label} must be an array of player ids.`,
    )
  }

  return value as string[]
}

/**
 * Catalog v1 generated by the Python engine is stored with
 * snake_case match keys:
 *
 *   team_a / team_b / sitouts
 *
 * The STM fairness/generation domain uses:
 *
 *   teamA / teamB / restingPlayerIds
 *
 * Normalize once at the repository boundary so every downstream
 * consumer keeps using the existing STM domain model.
 *
 * The function is intentionally backward compatible with older
 * catalog rows that are already stored in camelCase.
 */
function normalizeTemplateSchedule(
  value: unknown,
): IndividualRotationTemplateRecord["schedule"] {
  const schedule =
    asRecord(value, "schedule")

  if (!Array.isArray(schedule.rounds)) {
    throw new Error(
      "Invalid Individual Rotation template: schedule.rounds must be an array.",
    )
  }

  const rounds =
    schedule.rounds.map(
      (rawRound, roundIndex) => {
        const round =
          asRecord(
            rawRound,
            `round ${roundIndex + 1}`,
          )

        if (!Array.isArray(round.matches)) {
          throw new Error(
            `Invalid Individual Rotation template: round ${roundIndex + 1}.matches must be an array.`,
          )
        }

        const matches =
          round.matches.map(
            (rawMatch, matchIndex) => {
              const match =
                asRecord(
                  rawMatch,
                  `round ${roundIndex + 1}, match ${matchIndex + 1}`,
                )

              const roundNumber =
                readRoundNumber(
                  round,
                  roundIndex + 1,
                )

              return {
                ...match,
                roundNumber,
                teamA: readPlayerPair(
                  match,
                  "teamA",
                  "team_a",
                  `round ${roundIndex + 1}, match ${matchIndex + 1}.teamA`,
                ),
                teamB: readPlayerPair(
                  match,
                  "teamB",
                  "team_b",
                  `round ${roundIndex + 1}, match ${matchIndex + 1}.teamB`,
                ),
              }
            },
          )

        return {
          ...round,
          roundNumber: readRoundNumber(
            round,
            roundIndex + 1,
          ),
          matches,
          restingPlayerIds:
            readRestingPlayerIds(
              round,
              `round ${roundIndex + 1}.restingPlayerIds`,
            ),
        }
      },
    )

  const normalizedSchedule: IndividualRotationTemplateRecord["schedule"] = {
    ...schedule,
    rounds,
  }

  return normalizedSchedule
}

export async function upsertIndividualRotationTemplates(
  records: readonly IndividualRotationTemplateRecord[],
): Promise<void> {
  if (!records.length) return

  const supabase = await createClient()

  const { error } = await supabase
    .from("individual_rotation_templates")
    .upsert(
      records.map((record) => ({
        player_count: record.playerCount,
        usable_court_count:
          record.usableCourtCount,
        seed_count: record.seedCount,
        round_count: record.roundCount,
        engine_version:
          record.engineVersion,
        schedule: record.schedule,
        metrics: record.metrics,
        raw_penalty: record.rawPenalty,
        theoretical_floor:
          record.theoreticalFloor,
        fairness_score:
          record.fairnessScore,
        generated_at:
          new Date().toISOString(),
      })),
      {
        onConflict:
          "player_count,usable_court_count,seed_count,round_count,engine_version",
      },
    )

  if (error) {
    throw new Error(error.message)
  }
}

export async function listIndividualRotationTemplates(input: {
  playerCount: number
  usableCourtCount: number
  seedCount: number
  engineVersion: string
}) {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from("individual_rotation_templates")
    .select("*")
    .eq(
      "player_count",
      input.playerCount,
    )
    .eq(
      "usable_court_count",
      input.usableCourtCount,
    )
    .eq(
      "seed_count",
      input.seedCount,
    )
    .eq(
      "engine_version",
      input.engineVersion,
    )
    .order(
      "round_count",
      { ascending: true },
    )

  if (error) {
    throw new Error(error.message)
  }

  return data ?? []
}

export async function getIndividualRotationTemplate(input: {
  playerCount: number
  usableCourtCount: number
  seedCount: number
  roundCount: number
  engineVersion: string
}): Promise<IndividualRotationTemplateRecord | null> {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from("individual_rotation_templates")
    .select("*")
    .eq(
      "player_count",
      input.playerCount,
    )
    .eq(
      "usable_court_count",
      input.usableCourtCount,
    )
    .eq(
      "seed_count",
      input.seedCount,
    )
    .eq(
      "round_count",
      input.roundCount,
    )
    .eq(
      "engine_version",
      input.engineVersion,
    )
    .maybeSingle()

  if (error) {
    throw new Error(error.message)
  }

  if (!data) {
    return null
  }

  return {
    playerCount:
      data.player_count,
    usableCourtCount:
      data.usable_court_count,
    seedCount:
      data.seed_count,
    roundCount:
      data.round_count,
    engineVersion:
      data.engine_version,
    schedule:
      normalizeTemplateSchedule(
        data.schedule,
      ),
    metrics:
      data.metrics,
    rawPenalty:
      data.raw_penalty,
    theoreticalFloor:
      data.theoretical_floor,
    fairnessScore:
      data.fairness_score,
  } as IndividualRotationTemplateRecord
}

export async function listIndividualRotationTemplateCoverage(input: {
  minPlayers: number
  maxPlayers: number
  engineVersion: string
}) {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from("individual_rotation_templates")
    .select(
      "player_count,usable_court_count,seed_count,round_count",
    )
    .gte(
      "player_count",
      input.minPlayers,
    )
    .lte(
      "player_count",
      input.maxPlayers,
    )
    .eq(
      "engine_version",
      input.engineVersion,
    )

  if (error) {
    throw new Error(error.message)
  }

  return data ?? []
}
