import type { BracketEntry } from "./BracketEntry";
import type { BracketMatch } from "./BracketMatch";
import type { BracketRound } from "./BracketRound";

/**
 * Root object representing an entire bracket.
 *
 * This is the immutable domain model generated by the
 * BracketBuilder and consumed by:
 *
 * - Repository
 * - UI
 * - Print
 * - Live Manager
 */
export interface BracketTree {

  /**
   * Unique bracket identifier.
   */
  id: string;

  /**
   * Engine identifier.
   *
   * Example:
   * "single-elimination"
   */
  engineType: string;

  /**
   * Bracket size.
   *
   * Examples:
   * 4
   * 8
   * 16
   * 32
   */
  size: number;

  /**
   * Original competition entries.
   */
  entries: BracketEntry[];

  /**
   * Ordered rounds.
   */
  rounds: BracketRound[];

  /**
   * Flat list of all matches.
   *
   * Useful for lookups without traversing rounds.
   */
  matches: BracketMatch[];

  /**
   * Winner of the competition.
   *
   * Undefined until the tournament is completed.
   */
  winnerEntryId?: string;

  /**
   * Additional engine information.
   */
  metadata?: Record<string, unknown>;
}